Rest api
SIGMusic/musicMaker-backend pull request #25
Opened 2019-03-30 23:04 UTC by melissachen2000

Should now be working, pending changes from the parser. Format is as specified before.

2019-03-30 23:18 UTC, pianobin requested changes

2019-03-30 23:18 UTC, PianoBin commented on .gitignore
> +>>>>>>> f8e634648ba88348ff11d616d53a7d81182c5b9d
Merge conflict in gitignore :/

2019-03-30 23:19 UTC, PianoBin commented
Also, can we put all the .idea* config files in the .gitignore?

2019-03-31 00:14 UTC, melissachen2000 commented on .gitignore
> +>>>>>>> f8e634648ba88348ff11d616d53a7d81182c5b9d
Should be resolved

2019-03-31 05:10 UTC, pianobin approved these changes

2019-03-31 05:10 UTC, merged